module.exports = {
  rules: {
    'arrow-body-style': ['error', 'as-needed'],
    'arrow-parens': ['error', 'always'],
    'arrow-spacing': 'error',
    'constructor-super': 'error',
    'generator-star-spacing': ['error', { before: false, after: true }],
    'no-class-assign': 'error',
    'no-confusing-arrow': 'error',
    'no-const-assign': 'error',
    'no-dupe-class-members': 'error',
    'no-duplicate-imports': 'error',
    'no-new-symbol': 'error',
    // 'no-restricted-exports': [
    //   'error',
    //   {
    //     restrictedNamedExports: ['foo', 'bar'],
    //   },
    // ],
    // 'no-restricted-imports': ['error', 'import1', 'import2'],
    'no-this-before-super': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-constructor': 'error',
    'no-useless-rename': 'error',
    'no-var': 'error',
    'object-shorthand': ['error', 'always'],
    'prefer-arrow-callback': 'error',
    'prefer-const': 'error',
    'prefer-destructuring': 'error',
    'prefer-numeric-literals': 'error',
    'prefer-rest-params': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'require-yield': 'error',
    // 'rest-spread-spacing': 'error',
    // 'sort-imports': 'error',
    'symbol-description': 'error',
    'template-curly-spacing': ['error', 'always'],
    'yield-star-spacing': ['error', { before: false, after: true }],
  },
}
